"""1

Revision ID: 6291a612fc85
Revises: 
Create Date: 2020-05-03 13:56:18.298536

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6291a612fc85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=True),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('question',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.Column('single_answer', sa.Boolean(), nullable=True),
    sa.Column('img', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['manager'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('manager', sa.Integer(), nullable=True),
    sa.Column('create_on', sa.DateTime(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['manager'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('answer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_in_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_list', sa.Integer(), nullable=True),
    sa.Column('question', sa.Integer(), nullable=True),
    sa.Column('Балы за вопрос', sa.Integer(), nullable=True),
    sa.Column('Время на ответ в минутах', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question'], ['question.id'], ),
    sa.ForeignKeyConstraint(['question_list'], ['question_list.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('question_list', 'question', name='_question_list_question_uc')
    )
    op.create_table('questionlists',
    sa.Column('questionlist_id', sa.Integer(), nullable=True),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['question_id'], ['question.id'], ),
    sa.ForeignKeyConstraint(['questionlist_id'], ['question_list.id'], )
    )
    op.create_table('user_question_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('questionlist', sa.Integer(), nullable=True),
    sa.Column('star_time', sa.DateTime(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['questionlist'], ['question_list.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'questionlist', name='_user_questionlist_uc')
    )
    op.create_table('user_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('q_in_l', sa.Integer(), nullable=True),
    sa.Column('q_start_time', sa.DateTime(), nullable=True),
    sa.Column('is_success', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['q_in_l'], ['question_in_list.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_answers')
    op.drop_table('user_question_list')
    op.drop_table('questionlists')
    op.drop_table('question_in_list')
    op.drop_table('answer')
    op.drop_table('user_roles')
    op.drop_table('question_list')
    op.drop_table('question')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('role')
    # ### end Alembic commands ###
