"""empty message

Revision ID: 99ef7d60d716
Revises: 6291a612fc85
Create Date: 2020-05-05 12:14:48.164539

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99ef7d60d716'
down_revision = '6291a612fc85'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_question_list')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_question_list',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('user', sa.INTEGER(), nullable=True),
    sa.Column('questionlist', sa.INTEGER(), nullable=True),
    sa.Column('star_time', sa.DATETIME(), nullable=True),
    sa.Column('is_success', sa.BOOLEAN(), nullable=True),
    sa.CheckConstraint('is_success IN (0, 1)'),
    sa.ForeignKeyConstraint(['questionlist'], ['question_list.id'], ),
    sa.ForeignKeyConstraint(['user'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user', 'questionlist', name='_user_questionlist_uc')
    )
    # ### end Alembic commands ###
