"""empty message

Revision ID: f6757a9a7102
Revises: 99ef7d60d716
Create Date: 2020-05-05 15:16:25.432014

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6757a9a7102'
down_revision = '99ef7d60d716'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('questionlistsdone',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('questionlist_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['questionlist_id'], ['question_list.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('questionlistsdone')
    # ### end Alembic commands ###
